<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.Hubris</RootNamespace>
    <AssemblyName>FIP_Hubris_Settings</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-Hubris\LoadFolders\Hubris\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
