<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.Whitespring</RootNamespace>
    <AssemblyName>FIP_Whitespring_Settings</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-Whitespring\LoadFolders\Whitespring\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
