<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.Lucky38</RootNamespace>
    <AssemblyName>FIP_Lucky38_Harmony</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-Lucky 38\LoadFolders\Harmony\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Settings\**\*.cs" />
  </ItemGroup>
</Project>
