<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.WestTek</RootNamespace>
    <AssemblyName>FIP_WestTek</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-WestTek\LoadFolders\WestTek\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Harmony\**\*.cs" />
  </ItemGroup>
</Project>
