<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.Lucky38</RootNamespace>
    <AssemblyName>FIP_Lucky38_Settings</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-Lucky 38\LoadFolders\Lucky38\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
