<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FIP.YesMan</RootNamespace>
    <AssemblyName>FIP_YesMan</AssemblyName>
    <OutputPath>$(FipReleaseRoot)FIP-Yes Man\1.6\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(RimWorldManagedDir)\UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
